import { AnalyzeResponse } from './api';

export const SAMPLE_ANALYSIS: AnalyzeResponse = {
  id: 'sample-demo-analysis',
  github_username: 'demo-developer',
  role_id: 'backend',
  role_name: 'Backend Developer',
  level: 'mid',
  readiness_score: 0.78,
  readiness_tier: 'ready',
  readiness_label: 'Hazır',
  total_repos_scanned: 3,
  relevant_repos_found: 3,
  created_at: new Date().toISOString(),
  skills: [
    {
      skill_id: 'api-design',
      skill_name: 'API Tasarımı & HTTP Mimarisi',
      score: 0.88,
      importance: 0.9,
      subskills: [
        {
          composite_key: 'api-design::fastapi-frameworks',
          subskill_name: 'FastAPI / Modern Web Frameworks',
          confidence: 0.92,
          status: 'evidence_found',
          evidence_sources: [
            'demo-ecommerce-api/src/main.py:24',
            'demo-ecommerce-api/src/routes/items.py:48',
          ],
        },
        {
          composite_key: 'api-design::restful-principles',
          subskill_name: 'RESTful API Prensipleri & Durum Kodları',
          confidence: 0.88,
          status: 'evidence_found',
          evidence_sources: [
            'demo-ecommerce-api/src/routes/orders.py:72',
            'demo-ecommerce-api/src/schemas/response.py:15',
          ],
        },
        {
          composite_key: 'api-design::graphql-schema',
          subskill_name: 'GraphQL & Schema Tasarımı',
          confidence: 0.0,
          status: 'not_yet_evidenced',
          evidence_sources: [],
        },
      ],
    },
    {
      skill_id: 'database-orm',
      skill_name: 'Veritabanı & ORM Modelleme',
      score: 0.82,
      importance: 0.85,
      subskills: [
        {
          composite_key: 'database-orm::postgresql-relational',
          subskill_name: 'PostgreSQL / İlişkisel Veritabanları',
          confidence: 0.85,
          status: 'evidence_found',
          evidence_sources: [
            'demo-ecommerce-api/src/database.py:18',
            'demo-ecommerce-api/alembic/versions/001_initial.py:12',
          ],
        },
        {
          composite_key: 'database-orm::sqlalchemy-async',
          subskill_name: 'SQLAlchemy / Async ORM',
          confidence: 0.82,
          status: 'evidence_found',
          evidence_sources: [
            'demo-ecommerce-api/src/models/order.py:34',
            'demo-ecommerce-api/src/repositories/base.py:22',
          ],
        },
        {
          composite_key: 'database-orm::indexing-optimization',
          subskill_name: 'Veritabanı İndeksleme & Optimizasyon',
          confidence: 0.0,
          status: 'not_yet_evidenced',
          evidence_sources: [],
        },
      ],
    },
    {
      skill_id: 'auth-security',
      skill_name: 'Kimlik Doğrulama & Güvenlik',
      score: 0.74,
      importance: 0.8,
      subskills: [
        {
          composite_key: 'auth-security::jwt-auth',
          subskill_name: 'JWT & Token Tabanlı Yetkilendirme',
          confidence: 0.86,
          status: 'evidence_found',
          evidence_sources: [
            'demo-auth-service/src/tokens.py:44',
            'demo-auth-service/src/middleware/jwt_bearer.py:19',
          ],
        },
        {
          composite_key: 'auth-security::oauth2-sso',
          subskill_name: 'OAuth2 & SSO Entegrasyonu',
          confidence: 0.72,
          status: 'evidence_found',
          evidence_sources: [
            'demo-auth-service/src/oauth.py:51',
          ],
        },
        {
          composite_key: 'auth-security::rate-limiting',
          subskill_name: 'Rate Limiting & DDoS Koruması',
          confidence: 0.0,
          status: 'not_yet_evidenced',
          evidence_sources: [],
        },
      ],
    },
    {
      skill_id: 'testing-qa',
      skill_name: 'Birim & Entegrasyon Testleri',
      score: 0.70,
      importance: 0.75,
      subskills: [
        {
          composite_key: 'testing-qa::pytest-automation',
          subskill_name: 'Pytest & Test Otomasyonu',
          confidence: 0.80,
          status: 'evidence_found',
          evidence_sources: [
            'demo-auth-service/tests/test_tokens.py:12',
            'demo-ecommerce-api/tests/test_orders.py:28',
          ],
        },
        {
          composite_key: 'testing-qa::mocking-fixtures',
          subskill_name: 'Mocking & Fixture Yönetimi',
          confidence: 0.75,
          status: 'evidence_found',
          evidence_sources: [
            'demo-ecommerce-api/tests/conftest.py:15',
          ],
        },
        {
          composite_key: 'testing-qa::e2e-integration',
          subskill_name: 'E2E Entegrasyon Testleri',
          confidence: 0.0,
          status: 'not_yet_evidenced',
          evidence_sources: [],
        },
      ],
    },
  ],
  repos: [
    {
      repo_name: 'demo-ecommerce-api',
      repo_url: 'https://github.com/demo-developer/demo-ecommerce-api',
      description: 'Asynchronous REST API service built with FastAPI, PostgreSQL and Alembic migrations',
      primary_language: 'Python',
      languages: { Python: 85200, Dockerfile: 2100 },
      stars: 24,
      forks: 4,
      topics: ['fastapi', 'postgresql', 'asyncio', 'docker', 'rest-api'],
      is_relevant: true,
      relevant_files_count: 24,
      evidence_found: [
        'FastAPI dependency injection',
        'PostgreSQL async session',
        'Pydantic request validation',
        'Alembic migrations',
      ],
    },
    {
      repo_name: 'demo-order-worker',
      repo_url: 'https://github.com/demo-developer/demo-order-worker',
      description: 'Distributed task worker for asynchronous order processing, Redis queues, and notifications',
      primary_language: 'Python',
      languages: { Python: 42300 },
      stars: 11,
      forks: 1,
      topics: ['celery', 'redis', 'worker', 'microservices'],
      is_relevant: true,
      relevant_files_count: 12,
      evidence_found: [
        'Celery task orchestration',
        'Redis message broker',
        'Dead-letter queue handling',
      ],
    },
    {
      repo_name: 'demo-auth-service',
      repo_url: 'https://github.com/demo-developer/demo-auth-service',
      description: 'JWT-based authentication microservice with OAuth2 flows and Pytest coverage',
      primary_language: 'Python',
      languages: { Python: 31800 },
      stars: 18,
      forks: 2,
      topics: ['jwt', 'oauth2', 'security', 'pytest'],
      is_relevant: true,
      relevant_files_count: 16,
      evidence_found: [
        'RS256 JWT validation',
        'Password hashing with bcrypt',
        'Pytest unit & integration tests',
      ],
    },
  ],
};
